### ISSUE TITLE
Upgrade provider to 3.x version

### ISSUE THREAD

**Issue by pimielowski** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#147]
### Is your feature request related to a problem?

Hashicorp releases a new version of AzureRM provider 3.0, based on what is changed upgrade process should be easy.

Also they post couple of information:

`Note: Version 3.0 and 3.x versions of the AzureRM provider will be the last versions compatible with Terraform 0.12 - 0.15.`

`When upgrading to v3.0 of the AzureRM Provider, we recommend upgrading to the latest version of Terraform Core  - the next major release of the AzureRM Provider (v4.0) will require Terraform 1.0 or later.`
 

### Describe the solution you'd like

Upgrade existing codebase to never version of AzureRM provider.

### Describe alternatives you've considered

We can wait for version 4.x but I think that if we adopt early to the most recent version, we will be ready for the potential features to come with version 3.x.

**Comment by Dushelov** [comment]
+1 to this issue

**Comment by rokeno** [comment]
+1 - any update on this?
