### ISSUE TITLE
Fix terraform_fmt version consistency between CI and the Code

### ISSUE THREAD

**Issue by migara** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#149]

**Comment by FoSix** [comment]
@migara - I think we can close this one. It should be fixed along with [this PR](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/pull/148/files#diff-e076e43cb817ecc8b3c2ed18cd58baa50544ecc66293ed6e61129c43ca6a09cc). Unless there is something more to be done.
