### ISSUE TITLE
Release 0.3.0 missing in terraform registry

### ISSUE THREAD

**Issue by Dushelov** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#170]
## Describe the bug

Version 0.3.0 missing at https://registry.terraform.io/modules/PaloAltoNetworks/vmseries-modules/azurerm

## Expected behavior

Release 0.3.0 possible to use via terraform

## Current behavior

Release 0.3.0 not possible to use via terraform

## Possible solution

Publish release to registry

## Context

This is the last module that prevent us to upgrade to azurerm 3+ version

**Comment by migara** [comment]
Thanks for the report, it's now available via the [registry](https://registry.terraform.io/modules/PaloAltoNetworks/vmseries-modules/azurerm/0.3.0)
