### ISSUE TITLE
Improve checkov output in pre-commit.

### ISSUE THREAD

**Issue by pimielowski** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#200]
### Is your feature request related to a problem?

Right now we don't specify which test we want to check, and the result of that is whole errors which checkov makes are skipped because they touch something we don't need or wont to check.

### Describe the solution you'd like

We need to clarify which test we want to do with check and properly configure it.

**Comment by horiagunica** [comment]
## Pre-commit YAML modification

- Modified the checkov hook to exclude certain checks
- Update code to fix some checks


| Checkov ID      | Description | Status     |
| :---            |    :----:   |      :---: |
| CKV_AZURE_118   | Ensure that Network Interfaces disable IP forwarding | Excluded
| CKV_AZURE_119   | Ensure ‘Block Project-wide SSH keys’ is enabled for VM instances | Excluded
| CKV_AZURE_120   | Ensure that Application Gateway enables WAF | Excluded
| CKV2_AZURE_12   | Ensure that virtual machines are backed up using Azure Backup | Excluded
| CKV2_AZURE_10   | Ensure that Microsoft Antimalware is configured to automatically updates for Virtual Machines | Excluded
| CKV2_GHA_1      | Ensure top-level permissions are not set to write-all | Excluded

- The following should be confirmed before excluding them :

| Checkov ID      | Description | Status     |
| :---            |    :----:   |      :---: |
| CKV_AZURE_35    | Ensure default network access rule for Storage Accounts is set to deny | To be discussed



- The following will generate only softfails as warning (to be included in future features) :

| Checkov ID      | Description | Status     |
| :---            |    :----:   |      :---: |
| CKV_AZURE_93    | Ensure that managed disks use a specific set of disk encryption sets for the customer-managed key encryption | Soft Fail
| CKV2_AZURE_18   | Ensure that Storage Accounts use customer-managed key for encryption | Soft Fail
| CKV2_AZURE_1    | Ensure storage for critical data are encrypted with Customer Managed Key | Soft Fail
