### ISSUE TITLE
Bootstrap Example should use a sensitive variable

### ISSUE THREAD

**Issue by JustinGrote** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#205]
The bootstrap example encourages people checking secrets into the repo. This is a bad and dangerous practice.
https://developer.hashicorp.com/terraform/tutorials/configuration-language/sensitive-variables

It should instead use a sensitive variable and the `local_sensitive_file` resource to then upload to the storage account.

**Comment by FoSix** [comment]
@JustinGrote Thanks for you comments. I do agree with you, partially, but I do not exactly understand your solution. 

> The bootstrap example encourages people checking secrets into the repo
Yes, data that normally would be a secret, so passwords and config files are available in this repository as examples. But I would say it's up to one's common sense to avoid it in real life. Maybe this is not emphasised enough in the example's documentation. Maybe there should be a section in README (bootstrap but also others, as bootstrap is not the only place we use potentially dangerous data as examples) that will warn about the files and variables that should not be placed in a repository. That is maybe something that can be done better.

But please keep in mind that this is an example and should be treated as one - this is not production code.

> It should instead use a sensitive variable and the `local_sensitive_file`
That is a good point and we will definitively use it. But I do not see how this would prevent one from pushing these sensitive data to a repo. This will only hide this information from the CLI output. It will not help if someone (for example) will set up a poorly prepared `.gitignore` file.

Nevertheless, there are things to improve.
