### ISSUE TITLE
Example Alignment with Reference Architectures

### ISSUE THREAD

**Issue by migara** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#235]
We will need to rename/align our examples with our reference architectures. 

- [ ] https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/issues/228

**Comment by migara** [comment]
https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/issues/187

**Comment by migara** [comment]
This will be part of #251

**Comment by FoSix** [comment]
closed with #251
