### ISSUE TITLE
Deprecate Examples

### ISSUE THREAD

**Issue by migara** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#237]
Some old examples will become redundant after refactoring examples to align with our reference architectures.

We are planning to deprecate the below two examples in the near future 
- [Bootstrap](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/tree/main/examples/bootstrap)
- [vnet](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/tree/main/examples/vnet)

**Comment by migara** [comment]
#251

**Comment by FoSix** [comment]
closed with #251
