### ISSUE TITLE
Why use Public Loadbalancer

### ISSUE THREAD

**Issue by a83r** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#261]
### Is your feature request related to a problem?

I'm just curious why Palo uses everywhere public load balancers instead of gateway loadbalancers as these are specially made for this NVA use-case? Is there any reason I'm missing?

### Describe the solution you'd like

See above

**Comment by migara** [comment]
@a83r, thanks for the issue and the question. There is no preference of architecture one over the other, and this depends on the customer's requirements and the use case. If you're interested in taking a look at how we integrate with GWLB, there is a [PR](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/pull/227) for this.
