### ISSUE TITLE
add flexible names to all resources created by a module

### ISSUE THREAD

**Issue by FoSix** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#308]
- [ ] modify modules in a way that one can define a name for every resource created by a module
- [ ] figure out a way to replace `name_prefix` with a `name_template` map, for example
  ```terraform
  name_prefix = [
    env = "prod",
    preifx = "prefix"
    region = "northeu",
    bu = "RnD",
    name = "",
    suffix = true,
  ]
  ```
  Where `suffix` can be either a `string`, or a (for example) `bool` that would indicate a use of a hardcoded prefix (based on [this convention](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)).
  It should be also possible to change the order of elements in this list - a suffix does not have to be literally a suffix.

**Comment by FoSix** [comment]
an example imlementation:

```terraform
variable "name_delimiter" {
  description = <<-EOF
  A new variable that would be added to all examples.
  It specifies the delimiter used between all components of the new name.
  EOF
  type        = string
  default     = "-"
}

variable "name_template" {
  description = <<-EOF
  Replaces `var.name_prefix`.
  A list of maps, where keys are informational only.

  Important:
  1. %s will be eventually replaced by resource name
  2. __default__ is a marked that we should use a default resource abbreviation, anything else will be used literally.
  3. order matters

  EOF
  type        = list(map(string))
  default = [
    { prefix = "a_prefix" },
    { bu = "BU" },
    { abbreviation = "__default__" },
    { env = "prod" },
    { name = "%s" },
    { suffix = "01" },
  ]
}
variable "name" {
  description = <<-EOF
  The actual example resource name.
  Normally this will be a `name` property inside a map of resources.
  EOF
  type        = string
  default     = "hub-transit"
}

locals {
  # Here we create a template string from the name_template list
  name_template = join(
    var.name_delimiter,
    flatten(
      [for v in var.name_template : [
        for _, name_v in v : name_v
      ]]
    )
  )
}

output "out" {
  description = <<-EOF
  This code will be actually places in each module call, replacing the current:
  `name = "$\{var.name_prefix}$\{each.value.name}"`

  The example below is for a VNET, hence the `__default__` abbreviation placeholder is replaced with `vnet`.
  EOF
  value = replace(
    format(local.name_template, var.name),
    "__default__",
    "vnet"
  )
}

```

**Comment by FoSix** [comment]
if one would like to have the old approach, so just the `name_prefix`, the `name_template` variable should have a value of:
```terraform
 name_template = [
    { "name_prefix" = "a_prefix" },
    { name = "%s" }
  ] 
```

**Comment by sebastianczech** [comment]
I like that approach with `name_template`. Besides that I was thinking about default abbreviations - should we for every module define default values for abbreviations for every resource created in that module or maybe it's better to create new module only for storing map of all abbreviations in Azure ?

**Comment by FoSix** [comment]
> I like that approach with `name_template`. Besides that I was thinking about default abbreviations - should we for every module define default values for abbreviations for every resource created in that module or maybe it's better to create new module only for storing map of all abbreviations in Azure ?

I think having the abbreviations in a module would be troublesome. You cannot use a module as a function, meaning you cannot call a module in a one liner to produce an abbreviation for you.

**Comment by FoSix** [comment]
superseded by #307
