### ISSUE TITLE
[Bug Report] vmss backend_pool_id error pass in an array

### ISSUE THREAD

**Issue by PenDrag0n7** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#315]
### Describe the bug

I am trying to pass in the backend pool id but I am getting this error

│ Error: Invalid value for input variable
│
│   on main.tf line 141, in module "vmss":
│  141:   interfaces = [
│  142:     {
│  143:       name                = "public"
│  144:       subnet_id           = azurerm_subnet.subnet_public.id
│  145:       #lb_backend_pool_ids = module.loadbalancer.backend_pool_id
│  146:         lb_backend_pool_ids = [azurerm_lb_backend_address_pool.lb_backend.id]
│  147:     },
│  148:     {
│  149:       name       = "management"
│  150:       subnet_id  = azurerm_subnet.subnet_mgmt.id
│  151:       create_pip = true
│  152:     },
│  153:     {
│  154:       name      = "private"
│  155:       subnet_id = azurerm_subnet.subnet_private.id
│  156:     }
│  157:   ]
│
│ The given value is not suitable for module.vmss.var.interfaces declared at .terraform\modules\vmss\modules\vmss\variables.tf:22,1-22: attribute types must all match for conversion to map.

### Module Version

1.0.6

### Terraform version

1.5.6

**Comment by migara** [comment]
You will have to make sure you're using an approach similar to [here](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/blob/f3451232fb8b1ee0d32d15194805015a9f4f2de3/examples/common_vmseries_and_autoscale/main.tf#L209-L218)

The list you're passing here is converted into a map within the `vmss` module.
>attribute types must all match for conversion to map

**Comment by FoSix** [comment]
stale, closing for now
